### ISSUE TITLE
Showing hidden "Ultimate Performance" scheme for Windows 10 & 11

### ISSUE THREAD

**Issue by byyxx128** [tarcode-apps/BatteryMode#33]
Windows 10 as well as Windows 11 should have a hidden scheme "Ultimate Performance".

Battery Mode currently does not show it by default.

Is it possible to show it?

**Comment by byyxx128** [comment]
Currently, I can get it out by importing the following registry.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\User\Default\PowerSchemes]
"ActivePowerScheme"="e9a42b02-d5df-448d-aa00-03f14749eb61"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\User\PowerSchemes]
"ActivePowerScheme"="e9a42b02-d5df-448d-aa00-03f14749eb61"
```
High authority may be necessary.

Most time it is only visible when it is active.

**Comment by byyxx128** [comment]
Currently, I can make it appear by importing the following registry.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\User\Default\PowerSchemes]
"ActivePowerScheme"="e9a42b02-d5df-448d-aa00-03f14749eb61"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\User\PowerSchemes]
"ActivePowerScheme"="e9a42b02-d5df-448d-aa00-03f14749eb61"
```
High authority may be necessary.

Most time it is only visible when it is active.

**Comment by artar94** [comment]
@byyxx128 The hidden "Ultimate Performance" scheme can be forced to show in Battery Mode, but unfortunately the API does not allow it to be activated.

You can duplicate this power scheme with powercfg:
```cmd
powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
```
Battery Mode will be able to work with it.

To undo this change, you can restore the default power schemes:
```cmd
powercfg -restoredefaultschemes
```
