### ISSUE TITLE
[Suggestion] Add windows 11 icon

### ISSUE THREAD

**Issue by BraINstinct0** [tarcode-apps/BatteryMode#36]
As of windows 11 (build 22000.176(latest Beta build)), the battery icon has been rounded & the plug is changed to be opaque.
Images are as below(for reference; it is captured, so will be low-res).
![image](https://user-images.githubusercontent.com/29201475/132277678-6e25fd1c-4792-4172-9303-66f60627f3ef.png)
![image](https://user-images.githubusercontent.com/29201475/132277685-f97a4d7b-eb9a-4624-89f0-d966216647a1.png)

If method to extract the source image is given, I'll upload those as well.

**Comment by artar94** [comment]
@BraINstinct0 Implemented in version https://github.com/tarcode-apps/BatteryMode/releases/tag/v4.2.0.178
