### ISSUE TITLE
Some of the Japanese translations have not been applied to the build.

### ISSUE THREAD

**Issue by a1678991** [tarcode-apps/BatteryMode#49]
I have added a new `Localization/Japanese/JapaneseSettings.rc` in https://github.com/tarcode-apps/BatteryMode/pull/47, but it is still in English as of 4.3.0.184.
![image](https://user-images.githubusercontent.com/7441512/150649821-4b1bc21a-7247-4982-af98-c0e012b6d736.png)

**Comment by artar94** [comment]
@a1678991 Sorry, I'm a little hasty with the release. Please try this beta https://dl.tarcode.ru/beta/4.3.0.185

**Comment by a1678991** [comment]
I have confirmed that there are no Japanese language issues with this build.
