### ISSUE TITLE
4.3.0.191 - Feedback

### ISSUE THREAD

**Issue by bovirus** [tarcode-apps/BatteryMode#59]
@artar94

![BatteryMode 4 3 0 191 - Installer - 01](https://user-images.githubusercontent.com/1262554/154092988-e535c8e1-b4f4-471e-89be-a15709bfccd5.jpg)

In exe -> File properties -> Version seems not right.

![BatteryMode 4 3 0 191 - Installer - 02](https://user-images.githubusercontent.com/1262554/154093075-5684034c-82b1-42fd-afc9-1376d0c624f5.jpg)

In the top left text is misisng program version
 

![BatteryMode 4 3 0 191 - GUI - 01](https://user-images.githubusercontent.com/1262554/154093178-01819465-7bd7-47a5-bcb9-4882d446ea72.jpg)

One string not translated

![BatteryMode 4 3 0 191 - GUI - 02](https://user-images.githubusercontent.com/1262554/154093228-06829ce5-917b-4efc-a388-ac484fdc73da.jpg)

Two strings not translated.

**Comment by bovirus** [comment]
@artar94 

No fixed in 4.3.0.192.

**Comment by artar94** [comment]
@bovirus It's not a mistake, it was meant to be. We do not translate the buttons on the keyboard.

**Comment by bovirus** [comment]
@artar94 

If iin italian keybaord the key is "Canc" or "Pausa" you cannot leave untranslated.

**Comment by artar94** [comment]
@bovirus Sorry for the long answer. Could you translate the following lines?
https://github.com/tarcode-apps/BatteryMode/blob/342229d73bbb17cc0bc7176231585ac6641e2796/Localization/Italian/ItalianHotKey.rc#L14-L35

**Comment by bovirus** [comment]
@artar94

360, "Canc"
361, "Maiusc"
362, "Alt"
363, "Win"
364, "Esc"
365, "Tab"
366, "Backspace"
367, "Invio"
368, "Stamp"
369, "Blocco Maiusc"
370, "Blocco Scorr"
371, "Pausa"
372, "Home"
373, "Fine"
374, "Canc"
375, "Ins"
376, "Pagina Su"
377, "Pagina Giù"
378, "Su"
379, "Destra"
380, "Giù"
381, "Sinistra"

Thanks.

**Comment by artar94** [comment]
@bovirus Lines 360 and 374 must be different

**Comment by bovirus** [comment]
@artar94 

On my italian keybaord I have

"Canc" button below "Ins" button
"Canc"/":" button on numeric keyboard on left of "0"/"ins" button

**Comment by artar94** [comment]
@bovirus What are the names of buttons 1 and 2 on your keyboard?
![image](https://user-images.githubusercontent.com/5181651/165799178-34fc6ada-60e0-446c-b12c-be3d50a7ecfa.png)

**Comment by bovirus** [comment]
1 = Ctrl
2 = Canc

**Comment by artar94** [comment]
@bovirus Please try this beta https://dl.tarcode.ru/beta/4.3.0.195

**Comment by bovirus** [comment]
@artar94 

Two problems about installer

![image](https://user-images.githubusercontent.com/1262554/165825297-cf9b43db-74f0-4830-9ca1-ca38dc97a22e.png)

![image](https://user-images.githubusercontent.com/1262554/165825336-a1f7527c-2d2b-4861-91d3-b3256e6ac33c.png)
