### ISSUE TITLE
Windows 7 8 8 Light icons do not look like the original  for Windows light theme

### ISSUE THREAD

**Issue by minsk21** [tarcode-apps/BatteryMode#65]
v 4.3.0.192

Windows 7 8 8 Light icons do not look like the original - they **have a stroke** around the outline

![image](https://user-images.githubusercontent.com/26014600/175102322-c51144fe-e51b-4c8f-9dcf-f4a3a603ad8d.png)

**Comment by artar94** [comment]
Removed the shadow of the icons. Please try this beta https://dl.tarcode.ru/beta/4.3.1.203
